name="blog"
version="0.1.1"
author="qxg"
email="qinxiaoguang01@gmail.com"

[redis]
ip="127.0.0.1"
port=6379

[server]
port=8080
page_url="http://qxgzone.com"
server_url="http://qxgzone.com:8080"

[mongo]
ip="127.0.0.1"
port=27017
db_name="blog"

[github]
client_id="eccd2bd134009643887a"
client_secret="f6e54592ac4561f73477544786a9846e9108ae44"